name: Micronaut Services

on:
  pull_request:
    paths:
      - 'applications/employee_access/**'
      - 'applications/employee_directory/**'
  workflow_dispatch:
    inputs:
      project:
        description: 'Select the project to build'
        required: true
        type: choice
        options:
          - employee_access
          - employee_directory

jobs:
  detect:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      employee_access_changed: ${{ steps.filter.outputs.employee_access }}
      employee_directory_changed: ${{ steps.filter.outputs.employee_directory }}
    steps:
      - uses: actions/checkout@v3
      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            employee_access:
              - 'applications/employee_access/**'
            employee_directory:
              - 'applications/employee_directory/**'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: detect
    strategy:
      matrix:
        project: [employee_access, employee_directory]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build Project ${{ matrix.project }}
        if: >
          (github.event_name == 'workflow_dispatch' && github.event.inputs.project == matrix.project)
          ||
          (github.event_name != 'workflow_dispatch' &&
            ((matrix.project == 'employee_access' && needs.detect.outputs.employee_access_changed == 'true') ||
             (matrix.project == 'employee_directory' && needs.detect.outputs.employee_directory_changed == 'true')))
        run: |
          echo "Building project: ${{ matrix.project }}"
          cd applications/${{ matrix.project }}
          chmod +x gradlew
          ./gradlew build
