name: Build Micronaut Projects

on:
  pull_request:
    paths:
      - 'alpha/**'
      - 'bravo/**'
  workflow_dispatch:
    inputs:
      project:
        description: 'Select project to build'
        required: true
        type: choice
        options:
          - alpha
          - bravo

jobs:
  detect:
    name: Detect Changed Paths
    runs-on: ubuntu-latest
    outputs:
      alpha_changed: ${{ steps.filter.outputs.alpha }}
      bravo_changed: ${{ steps.filter.outputs.bravo }}
    steps:
      - uses: actions/checkout@v3
      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            alpha:
              - 'alpha/**'
            bravo:
              - 'bravo/**'

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: detect
    strategy:
      matrix:
        project: [alpha, bravo]
    # Conditional:  
    # - For manual trigger (workflow_dispatch): run only if the input matches the matrix project.  
    # - For PR trigger: run only if the "detect" job flagged that project as changed.
    if: >
      (github.event_name == 'workflow_dispatch' && github.event.inputs.project == matrix.project)
      ||
      (github.event_name != 'workflow_dispatch' &&
        ((matrix.project == 'alpha' && needs.detect.outputs.alpha_changed == 'true') ||
         (matrix.project == 'bravo' && needs.detect.outputs.bravo_changed == 'true')))
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build Project ${{ matrix.project }}
        run: |
          echo "Building project: ${{ matrix.project }}"
          cd ${{ matrix.project }}
          ./gradlew build
