name: Destroy AWS infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'confirm' to proceed with destruction"
        required: true
        default: "cancel"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Verify confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "confirm" ]; then
            echo "Destruction not confirmed. Exiting..."
            exit 1
          fi
      
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        run: |
          echo "Set AWS credentials from GitHub Secrets"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Terraform initialize
        run: terraform init
        working-directory: infrastructure/aws

      - name: Terraform destroy
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve
        working-directory: infrastructure/aws
